services:
  # Model Server - Stores and serves PyTorch models
  model-server:
    build: ./model-server
    ports:
      - "5001:5000"
    volumes:
      - ./model-server:/app
      - ./lib:/app/lib
      - model-data:/data/models
    environment:
      - MODEL_DIRECTORY=/data/models
    networks:
      - ai-ml-network

  # Inference Server - Provides inference API for models
  inference-server:
    build: ./inference-server
    ports:
      - "5002:5000"
    volumes:
      - ./inference-server:/app
      - ./lib:/app/lib
    depends_on:
      - model-server
    environment:
      - MODEL_SERVER_URL=http://model-server:5000
    networks:
      - ai-ml-network
      - oran-sc-ric_ric_network

  # Analysis and Training Environment - Jupyter Lab for data analysis and model training
  analysis-and-training:
    build: ./analysis-and-training
    ports:
      - "8888:8888"
    volumes:
      - ./analysis-and-training:/app
      - ./lib:/app/lib
    depends_on:
      - model-server
      - inference-server
    environment:
      - MODEL_SERVER_URL=http://model-server:5000
      - INFERENCE_SERVER_URL=http://inference-server:5000
    networks:
      - ai-ml-network
      - oran-sc-ric_ric_network
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

  # Experiment Runner - Runs experiments against the RIC platform
  experiment-runner:
    build: ./experiment-runner
    volumes:
      - ./experiment-runner:/app
      - ./lib:/app/lib
      - ./analysis-and-training:/app/analysis-and-training
    depends_on:
      - model-server
      - inference-server
    environment:
      - MODEL_SERVER_URL=http://model-server:5000
      - INFERENCE_SERVER_URL=http://inference-server:5000
    networks:
      - ai-ml-network
      - oran-sc-ric_ric_network
    command: python /app/run_experiment.py --mode=test

networks:
  ai-ml-network:
    driver: bridge
  oran-sc-ric_ric_network:
    external: true

volumes:
  model-data: