services:
  # InfluxDB - Time series database for network metrics
  influxdb:
    container_name: metrics_influxdb
    hostname: metrics_influxdb
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=ric_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=ric_password
      - DOCKER_INFLUXDB_INIT_ORG=ric
      - DOCKER_INFLUXDB_INIT_BUCKET=network_metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ric_admin_token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - ai-ml-network
      - oran-sc-ric_ric_network

  # Model Server - Stores and serves PyTorch models
  model-server:
    build: ./model-server
    ports:
      - "5001:5000"
    volumes:
      - ./model-server:/app
      - model-data:/data/models
    environment:
      - MODEL_DIRECTORY=/data/models
    networks:
      - ai-ml-network

  # Inference Server - Provides inference API for models
  inference-server:
    build: ./inference-server
    ports:
      - "5002:5000"
    volumes:
      - ./inference-server:/app
    depends_on:
      - model-server
    environment:
      - MODEL_SERVER_URL=http://model-server:5000
    networks:
      - ai-ml-network
      - oran-sc-ric_ric_network

  # Analysis and Training Environment - Jupyter Lab for data analysis and model training
  analysis-and-training:
    build: ./analysis-and-training
    ports:
      - "8888:8888"
    volumes:
      - ./analysis-and-training:/app
    depends_on:
      - model-server
      - inference-server
    environment:
      - MODEL_SERVER_URL=http://model-server:5000
      - INFERENCE_SERVER_URL=http://inference-server:5000
    env_file:
      - .env
    networks:
      - ai-ml-network
      - oran-sc-ric_ric_network
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

networks:
  ai-ml-network:
    driver: bridge
  oran-sc-ric_ric_network:
    external: true

volumes:
  model-data:
  influxdb-data: